name: Suggest an idea
description: A feature or an improvement.
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: The need
      description: What problem does it solve, in what situation?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What you have in mind
