import AppKit
import Testing
@testable import Plume

/// Ce que la dictée laisse dans le presse-papiers, sans rien simuler au clavier. Toujours un
/// presse-papiers nommé, jamais le général : l'utilisateur ne perd rien pendant les tests.
@Suite("Presse-papiers")
@MainActor
struct PasterTests {
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private func withPasteboard(_ body: (NSPasteboard) -> Void) {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("plume-tests-\(UUID().uuidString)"))
        defer { pasteboard.releaseGlobally() }
        body(pasteboard)
    }

    @Test func uneDictéeQuiSeraRemplacéePorteLesMarquesÉphémères() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            pasteboard.setString("contenu d'avant", forType: .string)
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard)
            #expect(pasteboard.pasteboardItems?.count == 1)
            #expect(pasteboard.string(forType: .string) == "la dictée")
            #expect(pasteboard.types?.contains(Self.transient) == true)
            #expect(pasteboard.types?.contains(Self.autoGenerated) == true)
            #expect(saved?.count == 1)
            #expect(saved?.first?.string(forType: .string) == "contenu d'avant")
        }
    }

    @Test func uneDictéeQuiResteAppartientAuxGestionnaires() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            pasteboard.setString("contenu d'avant", forType: .string)
            let saved = Paster.stage("la dictée", restoreClipboard: false, on: pasteboard)
            #expect(saved == nil)
            #expect(pasteboard.string(forType: .string) == "la dictée")
            #expect(pasteboard.types?.contains(Self.transient) == false)
            #expect(pasteboard.types?.contains(Self.autoGenerated) == false)
        }
    }

    @Test func uneCopieSimpleNePortePasDeMarque() {
        withPasteboard { pasteboard in
            Paster.copy("texte", to: pasteboard)
            #expect(pasteboard.pasteboardItems?.count == 1)
            #expect(pasteboard.string(forType: .string) == "texte")
            #expect(pasteboard.types?.contains(Self.transient) == false)
        }
    }

    /// Tout revient, pas seulement le texte : plusieurs éléments, plusieurs formats chacun. Un
    /// texte mis en forme ou une image ne doivent pas redevenir du texte brut.
    @Test func leContenuDAvantRevientAprèsLeCollage() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            let first = NSPasteboardItem()
            first.setString("contenu d'avant", forType: .string)
            first.setString("<b>contenu d'avant</b>", forType: .html)
            let second = NSPasteboardItem()
            second.setString("deuxième élément", forType: .string)
            pasteboard.writeObjects([first, second])
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard) ?? []
            Paster.restore(saved, to: pasteboard, ifUnchangedSince: pasteboard.changeCount)
            let items = pasteboard.pasteboardItems ?? []
            #expect(items.count == 2)
            #expect(items.first?.string(forType: .string) == "contenu d'avant")
            #expect(items.first?.string(forType: .html) == "<b>contenu d'avant</b>")
            #expect(items.last?.string(forType: .string) == "deuxième élément")
            #expect(pasteboard.types?.contains(Self.transient) == false)
        }
    }

    @Test func unPressePapiersVideRedevientVide() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard)
            #expect(saved?.isEmpty == true)
            #expect(pasteboard.types?.contains(Self.transient) == true)
            Paster.restore(saved ?? [], to: pasteboard, ifUnchangedSince: pasteboard.changeCount)
            #expect(pasteboard.string(forType: .string) == nil)
        }
    }

    @Test func uneCopieFaiteEntreTempsResteEnPlace() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            pasteboard.setString("contenu d'avant", forType: .string)
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard) ?? []
            let marker = pasteboard.changeCount
            pasteboard.clearContents()
            pasteboard.setString("copié entre-temps", forType: .string)
            Paster.restore(saved, to: pasteboard, ifUnchangedSince: marker)
            #expect(pasteboard.string(forType: .string) == "copié entre-temps")
        }
    }
}
